apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: hello-openshift
  app.kubernetes.io/part-of: hello-openshift-product
resources:
- hello-openshift.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - env.properties
  name: hello-openshift-config
namespace: default