apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
spec:
  match:
    - excludedNamespaces:
        - "gatekeeper-system"
        - "kube*"
        - kube-node-lease
        - kube-public
        - kube-system
        - "openshift*"
        - openshift
        - openshift-apiserver
        - openshift-apiserver-operator
        - openshift-authentication
        - openshift-authentication-operator
        - openshift-cloud-credential-operator
        - openshift-cluster-csi-drivers
        - openshift-cluster-machine-approver
        - openshift-cluster-node-tuning-operator
        - openshift-cluster-samples-operator
        - openshift-cluster-storage-operator
        - openshift-cluster-version
        - openshift-config
        - openshift-config-managed
        - openshift-config-operator
        - openshift-console
        - openshift-console-operator
        - openshift-console-user-settings
        - openshift-controller-manager
        - openshift-controller-manager-operator
        - openshift-dns
        - openshift-dns-operator
        - openshift-etcd
        - openshift-etcd-operator
        - openshift-gatekeeper-system
        - openshift-image-registry
        - openshift-infra
        - openshift-ingress
        - openshift-ingress-canary
        - openshift-ingress-operator
        - openshift-insights
        - openshift-kni-infra
        - openshift-kube-apiserver
        - openshift-kube-apiserver-operator
        - openshift-kube-controller-manager
        - openshift-kube-controller-manager-operator
        - openshift-kube-scheduler
        - openshift-kube-scheduler-operator
        - openshift-kube-storage-version-migrator-operator
        - openshift-kubevirt-infra
        - openshift-machine-api
        - openshift-machine-config-operator
        - openshift-marketplace
        - openshift-monitoring
        - openshift-multus
        - openshift-network-diagnostics
        - openshift-network-operator
        - openshift-node
        - openshift-oauth-apiserver
        - openshift-openstack-infra
        - openshift-operator-lifecycle-manager
        - openshift-operators
        - openshift-ovirt-infra
        - openshift-sdn
        - openshift-service-ca
        - openshift-service-ca-operator
        - openshift-user-workload-monitoring
        - openshift-vsphere-infra
      processes:
        - '*'
  # In order to do analysis on other objects other than the one being analyzed we require syncing/caching turned on. https://open-policy-agent.github.io/gatekeeper/website/docs/sync
  # Also in the operator gatekeeper instance we require 
  #  audit:
  #    auditFromCache: Enabled
  sync:
    syncOnly:
      - group: ''
        kind: Namespace
        version: v1
      - group: apps.openshift.io
        kind: DeploymentConfig
        version: v1
      - group: ''
        kind: Service
        version: v1
      - group: route.openshift.io
        kind: Route
        version: v1