apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- svc.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: vault-demo
configMapGenerator:
- files:
  - application.properties
  name: app-config-cm
- files:
  - vault-agent-config.hcl
  name: vault-agent-config-cm