apiVersion: v1
kind: Service
metadata:
  name: xyz
  namespace: qa1-digital
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
