apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoDuplicateRoutes
metadata:
  name: noduplicateroutes
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]