kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: openshift-toolbox-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: openshift-toolbox
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 250m
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Max
    scaleUp: 
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 5 
        periodSeconds: 70
      - type: Percent
        value: 12 
        periodSeconds: 80
      selectPolicy: Max
