apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml
- configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: bluegreenstack
configMapGenerator:
- files:
  - config.json
  name: bluegreen-stack-config2
