apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fad
  namespace: qa1-digital
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: fad
    weight: 100
  wildcardPolicy: None