apiVersion: apps/v1
kind: Deployment
metadata:
  name: mamservices
  namespace: dev1-digital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mamservices
  template:
    metadata:
      labels:
        app: mamservices
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: mamservices-config
        