apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: providersearchdataservice
  namespace: dev1-digital
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: providersearchdataservice
    weight: 100
  wildcardPolicy: None