apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: xyz
  app.kubernetes.io/part-of: XYZProduct
resources:
- deployment.yaml
- svc.yaml
- route.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - env.properties
  name: xyz-config
namespace: dev1-digital
