apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: fad
  app.kubernetes.io/part-of: DIS
resources:
- deployment.yaml
- svc.yaml
- route.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - env.properties
  name: fad-config
namespace: dev1
