apiVersion: apps/v1
kind: Deployment
metadata:
  name: providersearchdataservice
  namespace: qa1-digital
spec:
  replicas: 3
  selector:
    matchLabels:
      app: providersearchdataservice
  template:
    metadata:
      labels:
        app: providersearchdataservice
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: providersearchdataservice-config
        