apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-with-annotations
  labels:
    app: devwebapp-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'example'
    vault.hashicorp.com/agent-inject-secret-myapp-config: 'secret/data/myapp/config'
spec:
  serviceAccountName: vault-auth
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      env:
        - name: VAULT_ADDR
          value: 'http://external-vault:8200'
        - name: VAULT_TOKEN
          value: root